### ISSUE TITLE
Support for not-prose

### ISSUE THREAD

**Issue by cschroeter** [milandekruijf/pandacss-preset-typography#1]
Hey mate.

Great stuff you have there. Do you plan to add `not-prose` support?

For reference: https://github.com/tailwindlabs/tailwindcss-typography/issues/32

**Comment by milandekruijf** [comment]
I do. I am currently working on it. The TailwindCSS plugin has also recevied some updates that I am shipping with the next update.

**Comment by milandekruijf** [comment]
Not-prose support has been added, thank you for the request.

**Comment by cschroeter** [comment]
This is really amazing. Goob job mate
