### ISSUE TITLE
Preset not working in a basic NextJS example

### ISSUE THREAD

**Issue by cschroeter** [milandekruijf/pandacss-preset-typography#2]
I tested your preset using Stackblitz or Codesandbox (can not recall) and it worked just fine. However trying to integrate in a Nextjs (or Astro) example app failed in the same way. 

Classname is `undefined` and styles are only applied partial

<img width="1296" alt="image" src="https://github.com/milandekruijf/pandacss-preset-typography/assets/1846056/3cd7065e-954d-4221-b271-7dc4ec39f956">

Reproduction Repo
https://github.com/cschroeter/panda-typo-bug-nextjs

I can also provide the Astro setup if you are interesed for troubleshooting.

**Comment by milandekruijf** [comment]
Thank you for creating the issue.

I am confident that it is the change from `name` to `className` for defining recipes since `v0.9.0` 
It should all be fixed in the next update I am hoping to get ready today.

**Comment by cschroeter** [comment]
Jup that rings a bell. I'm closing this since its obvious that this will be the fix. Thanks mate.
