### ISSUE TITLE
0.0.16 support

### ISSUE THREAD

**Issue by NiklasPor** [milandekruijf/pandacss-preset-typography#4]
I've installed it into my Qwik project with `@pandacss/dev` and it just doesn't seem to generate the code for the matching selector.

The recipe is generated, but the styling is not applied. In my tries it worked neither with or without a size.

```tsx
import { component$, Slot } from '@builder.io/qwik';
import { Box, Container, prose } from '@fancypage/styles';

export const MdxPage = component$(() => (
  <Container maxW="page" px="16">
    <Box class={prose({ size: 'lg' })}>
      <Slot />
    </Box>
  </Container>
));

```

**Comment by milandekruijf** [comment]
It's working fine on my end. Make sure you configured it correctly. Also, I am not sure how panda handles re-exports, so it might not even be able to detect that you have a prose call there.

**Comment by NiklasPor** [comment]
Interesting, I do everything via re-export – but maybe it's not working for recipes. I'll investigate further and add an update here if I manage to get it working.

**Comment by NiklasPor** [comment]
My bad, it was the reexport 🤦 Would have expected it to work, as it's also working for the defaults. Thanks!
