### ISSUE TITLE
Exposing the `createRecipe` function

### ISSUE THREAD

**Issue by astahmer** [milandekruijf/pandacss-preset-typography#5]
Hey, I'm currently using this preset with some customizations on my end, it looks like this:

```ts
className={cx(prose(), article(), css(xxx))}
```

prose is generated from `pandacss-preset-typography`
`article` is one of my config recipe

the issue is that some of my `article` styles are being overriden, due to the CSS specificity being the same between `prose` and `article`
so if you exposed the `createRecipe` I could create it and customize it directly on my end, that way there wouldnt be any clash because the `prose` styles that I'm trying to override would simply not be there anymore
(probably using the [recipe extension](https://github.com/chakra-ui/panda/pull/1414), or at least a deep merge)

**Comment by milandekruijf** [comment]
Hey! Sorry for the late response.

I've just published a new patch with more exposed functions, including the `createRecipe` function.

I hope it works out!

**Comment by milandekruijf** [comment]
I might do something with options to allow customisations within the preset options, but that might be something for in the future.

**Comment by astahmer** [comment]
thanks, that was fast !
